project:
  type: website
  output-dir: docs

website:
  title: "Kirstan Brodie"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: pubs.qmd
        text: Publications
      - href: CV.qmd
        text: CV
    tools:
      - icon: envelope
        href: mailto:klb322@cornell.edu
      - icon: twitter
        href: https://twitter.com/KirstanBrodie
      - icon: linkedin
        href: https://www.linkedin.com/in/kirstanbrodie/

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
    link-external-newwindow: true
    
editor: visual

